### ISSUE TITLE
[EPIC] Complete modifications features for spells/liturgies

### ISSUE THREAD

**Issue by SigurdJanson** [SigurdJanson/FateExplorer#160]
* [x] Show number of modifications allowed for spells / liturgies
* [ ] Add disallowed spells / liturgies to data base (some of them explicitely forbid certain modifications)
* [ ] Show the exact modifications each spell / liturgy permits
   * Sometimes you need to keep in mind that certain **Enhancements** may revoke a prohibited modification. E.g. spells with rane "self" cannot modify range. However the enhancement "Affect Another" will change that and allows range "touch" which can be modified.
