### ISSUE TITLE
Find ways to improve startup performance [EPIC]

### ISSUE THREAD

**Issue by SigurdJanson** [SigurdJanson/FateExplorer#178]
Data download
* [ ] #109
* [ ] Reduce the number of data files. These are quite many at the moment.
   * [ ] Merge shop data file with melee and ranged weapons.
* [ ] Minify json files.

However, the data files are not reason for poor startup performance. These tipps try to reduce the amount of data sent over the network:

* [ ] Activate trimming
   * [ ] Remove dynamic types
* [ ] Add Brotli Compression 
   * see e.g. https://github.com/dotnet/aspnetcore/issues/42284#issuecomment-1236530684 
   * [Compression](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#compression)

But there are other issues. A [discussion on GitHub](https://github.com/dotnet/aspnetcore/issues/42284) tries to find out more.

* [ ] Try setting `<EmccInitialHeapSize>16777216</EmccInitialHeapSize>`. That could help on mobile devices. See [this issue](https://github.com/dotnet/runtime/pull/80849)
